"""
═══════════════════════════════════════════════════════════════════════════════
  lasso_decomposition.py
  ─────────────────────────────────────────────────────────────────────────────

  LASSO (Least Absolute Shrinkage and Selection Operator) modal decomposition
  for Lamb wave amplitude extraction.

  WHY LASSO OVER TIKHONOV (L2 regularisation)
  ─────────────────────────────────────────────
  Tikhonov minimises:   ||s - M·a||²  +  λ·||a||²   (L2 penalty)
  LASSO minimises:      ||s - M·a||²  +  λ·||a||₁   (L1 penalty)

  The L1 penalty drives amplitudes to exactly zero rather than just small.
  This is physically motivated: you expect only a FEW modes to be genuinely
  present at any given frequency. Most modes should have zero amplitude.

  For your second harmonic signal this matters a lot. At 2.66 MHz there
  are 18 possible modes but only a handful are actually generated by the
  nonlinear interaction. Tikhonov gives small non-zero amplitudes to all
  18. LASSO automatically identifies which ones are truly active by setting
  the rest to exactly zero. This gives you a cleaner, more interpretable
  result and better amplitude estimates for the active modes.

  HOW LASSO FINDS THE RIGHT λ
  ────────────────────────────
  We use cross-validation (LassoCV) which tries multiple λ values and
  picks the one that gives the best prediction on held-out data.
  This removes the need to manually tune λ — a key weakness of Tikhonov
  where the choice of regularization = 1e-4 was somewhat arbitrary.

  HOW TO READ THE RESULTS
  ────────────────────────
  - Modes with a_n = 0.0 exactly: LASSO decided they are not present
  - Modes with a_n ≠ 0: active modes, their envelope peak is A_n
  - Compare the active set between fundamental and 2nd harmonic files
    to understand which mode pairs are generated

═══════════════════════════════════════════════════════════════════════════════
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.signal import hilbert
from sklearn.linear_model import LassoCV, Lasso
import warnings
warnings.filterwarnings("ignore")

from decomposition_v9_1  import (
    load_file, load_dispersion, build_dictionary,
    envelope_peaks, verify_against_gt, normalise_matrix,
    FUNDAMENTAL_FILE, SECOND_HARM_FILE, DISP_FILES, PROPAGATION_MM
)


# ─────────────────────────────────────────────────────────────────────────────
#  LASSO SOLVER
# ─────────────────────────────────────────────────────────────────────────────

def solve_lasso(s, M, mode_names, n_cv_folds=5, verbose=True):
    """
    Solve s = M·a using LASSO with cross-validated λ selection.

    Parameters
    ----------
    s          : measured signal (already DC-removed and same length as M rows)
    M          : normalised modal matrix (N × n_modes)
    mode_names : list of mode names for M columns
    n_cv_folds : number of cross-validation folds for λ selection

    Returns
    -------
    amplitudes : dict {mode: physical amplitude scalar}
    lambda_opt : the λ selected by cross-validation
    active     : list of modes with non-zero amplitude

    WHAT CROSS-VALIDATION DOES HERE
    ─────────────────────────────────
    The signal is split into n_cv_folds chunks. For each candidate λ,
    the model is trained on (n-1) chunks and tested on the held-out chunk.
    The λ that minimises the average test error is selected.
    For a time-series signal this means temporal chunks — the model
    is tested on its ability to predict unseen time segments, which
    directly measures generalisation rather than overfitting.
    """
    s0, M_norm, scales = normalise_matrix(s, M)

    # LassoCV automatically searches over a path of lambda values
    lasso_cv = LassoCV(
        cv        = n_cv_folds,
        max_iter  = 10000,
        n_alphas  = 100,        # number of λ values to try
        fit_intercept = False,  # DC already removed
        random_state  = 42,
    )
    lasso_cv.fit(M_norm, s0)

    lambda_opt = float(lasso_cv.alpha_)
    a_sc       = lasso_cv.coef_

    # Rescale back to physical units
    a          = a_sc / scales

    amplitudes = {m: float(a[i]) for i, m in enumerate(mode_names)}
    active     = [m for m in mode_names if abs(amplitudes[m]) > 1e-12]

    if verbose:
        print(f"  λ selected by CV : {lambda_opt:.6f}")
        print(f"  Active modes     : {active}")
        print(f"  Zero modes       : {[m for m in mode_names if m not in active]}")

        # Condition number for diagnostics
        cond = np.linalg.cond(M_norm)
        print(f"  Condition number : {cond:.3e}")
        if cond > 1e6:
            print("  ⚠  High cond — amplitudes may be unreliable")

        # Residual
        rec   = M @ a
        resid = float(np.linalg.norm(s - rec) / (np.linalg.norm(s) + 1e-12))
        print(f"  Relative residual: {resid:.4f}")

    return amplitudes, lambda_opt, active


# ─────────────────────────────────────────────────────────────────────────────
#  RUN ONE FILE  (fundamental or second harmonic)
# ─────────────────────────────────────────────────────────────────────────────

def run_lasso(filepath, disp, label="", verbose=True):
    """
    Full LASSO pipeline for one signal file.

    Returns result dict with amplitudes, peaks, verification, and
    all intermediate arrays needed for plotting.
    """
    print(f"\n{'='*60}")
    print(f"  LASSO — {label}")
    print(f"{'='*60}")

    t, s, exc, fs, gt, f_centre = load_file(filepath)
    N = len(t)

    print(f"\n  Building modal dictionary...")
    modal_waveforms, info, M, mode_names = build_dictionary(
        disp, exc, fs, N, f_centre, PROPAGATION_MM)

    print(f"\n  Running LASSO with cross-validated λ...")
    amplitudes, lambda_opt, active = solve_lasso(s, M, mode_names, verbose=verbose)

    # Reconstruction
    rec = sum(amplitudes[m] * modal_waveforms[m]
              for m in mode_names if abs(amplitudes[m]) > 1e-12)

    # Envelope peaks for active modes only
    active_amps = {m: amplitudes[m] for m in active}
    peaks       = envelope_peaks(active_amps, modal_waveforms)

    # Print amplitude table
    print(f"\n  ── LASSO Amplitudes ────────────────────────────────────")
    print(f"  {'Mode':<8} {'a_n':>12} {'|Peak| (nm)':>13} "
          f"{'t_pred (μs)':>13} {'Status':>10}")
    print("  " + "─" * 60)
    for mode in mode_names:
        a_n    = amplitudes[mode]
        peak   = peaks.get(mode, 0.0)
        t_pred = info[mode]["t_pred"]
        t_str  = f"{t_pred:.2f}" if not np.isnan(t_pred) else "—"
        status = "ACTIVE" if mode in active else "zero"
        print(f"  {mode:<8} {a_n:>12.6f} {peak:>13.6f} "
              f"{t_str:>13} {status:>10}")

    # Verify against GT
    verify_results = verify_against_gt(amplitudes, modal_waveforms, gt, label)

    return {
        "t": t, "s": s, "rec": rec,
        "amplitudes": amplitudes, "peaks": peaks,
        "modal_waveforms": modal_waveforms, "info": info,
        "mode_names": mode_names, "active": active,
        "lambda_opt": lambda_opt, "f_centre": f_centre,
        "gt": gt, "verify": verify_results, "label": label,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  PLOTTING
# ─────────────────────────────────────────────────────────────────────────────

def plot_lasso(result_f, result_2f):
    """
    Four-panel plot for one pair of files (fundamental + 2nd harmonic).
    """
    fig = plt.figure(figsize=(16, 14))
    gs  = gridspec.GridSpec(4, 2, figure=fig, hspace=0.5, wspace=0.35)
    fig.suptitle(
        f"LASSO Modal Decomposition  |  d = {PROPAGATION_MM} mm\n"
        f"Fundamental f = {result_f['f_centre']:.3f} MHz  |  "
        f"2nd Harmonic 2f = {result_2f['f_centre']:.3f} MHz",
        fontsize=12)

    for col, result in enumerate([result_f, result_2f]):
        t   = result["t"]
        s   = result["s"]
        rec = result["rec"]
        resid = float(np.linalg.norm(s - rec) / (np.linalg.norm(s) + 1e-12))
        label = result["label"]

        # ── Row 0: signal vs reconstruction ──────────────────────────────
        ax = fig.add_subplot(gs[0, col])
        ax.plot(t, s,   color="steelblue", lw=0.8, alpha=0.8, label="Measured s(t)")
        ax.plot(t, rec, color="tomato", lw=1.2, ls="--",
                label=f"LASSO reconstruction  (resid={resid:.3f})")
        ax.set_title(f"{label}  —  Signal vs Reconstruction")
        ax.set_xlabel("Time (μs)"); ax.set_ylabel("nm")
        ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

        # ── Row 1: individual active mode contributions ───────────────────
        ax = fig.add_subplot(gs[1, col])
        ax.plot(t, s, color="black", lw=0.4, alpha=0.12, label="Measured")
        cmap = plt.cm.tab20(np.linspace(0, 1, max(len(result["active"]), 1)))
        for i, mode in enumerate(result["active"]):
            contrib = result["amplitudes"][mode] * result["modal_waveforms"][mode]
            env     = np.abs(hilbert(contrib))
            t_pred  = result["info"][mode]["t_pred"]
            lbl     = (f"{mode} ({t_pred:.1f}μs)"
                       if not np.isnan(t_pred) else mode)
            ax.plot(t, contrib, color=cmap[i], lw=1.0, label=lbl)
            ax.plot(t, env,     color=cmap[i], lw=0.7, ls=":", alpha=0.6)
        ax.set_title("Active mode contributions  (dotted = envelope)")
        ax.set_xlabel("Time (μs)"); ax.set_ylabel("nm")
        ax.legend(ncol=2, fontsize=7); ax.grid(True, alpha=0.3)

        # ── Row 2: amplitude bar chart ────────────────────────────────────
        ax      = fig.add_subplot(gs[2, col])
        modes   = result["mode_names"]
        vals    = [result["peaks"].get(m, 0.0) for m in modes]
        colors  = ["tomato" if m in result["active"] else "lightgrey"
                   for m in modes]
        bars    = ax.bar(modes, vals, color=colors, edgecolor="white")
        for bar, v in zip(bars, vals):
            if v > 0:
                ax.text(bar.get_x() + bar.get_width()/2, v*1.02,
                        f"{v:.4f}", ha="center", va="bottom",
                        fontsize=6, rotation=45)
        ax.set_title("Envelope peak amplitudes  (red=active, grey=LASSO zeroed)")
        ax.set_ylabel("|A| (nm)"); ax.grid(True, alpha=0.3, axis="y")
        ax.tick_params(axis="x", rotation=45)

        # ── Row 3: verification bar chart (if GT available) ───────────────
        ax = fig.add_subplot(gs[3, col])
        vr = result["verify"]
        if vr:
            vm     = sorted(vr.keys())
            gt_v   = [vr[m]["gt_peak"]  for m in vm]
            rec_v  = [vr[m]["rec_peak"] for m in vm]
            x      = np.arange(len(vm)); w = 0.38
            ax.bar(x - w/2, gt_v,  w, label="GT",        color="steelblue", alpha=0.85)
            ax.bar(x + w/2, rec_v, w, label="LASSO rec.", color="tomato",    alpha=0.85)
            ax.set_xticks(x); ax.set_xticklabels(vm, rotation=45, fontsize=8)
            ax.set_title("GT vs LASSO recovered amplitudes")
            ax.set_ylabel("nm"); ax.legend(fontsize=8)
            ax.grid(True, alpha=0.3, axis="y")
        else:
            ax.text(0.5, 0.5, "No GT available\n(experimental data)",
                    ha="center", va="center", transform=ax.transAxes, fontsize=11)
            ax.set_title("Verification")

    plt.savefig("plots/lasso_decomposition.png", dpi=200, bbox_inches="tight")
    print("\n  Saved: plots/lasso_decomposition.png")
    plt.show()


def plot_lasso_error_comparison(result_f, result_2f):
    """
    Error % bar chart comparing LASSO accuracy across all modes for
    both files. This is your Objective 2.3.1 validation figure.
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("LASSO Amplitude Error vs Ground Truth  |  "
                 f"d = {PROPAGATION_MM} mm", fontsize=12)

    for ax, result in zip(axes, [result_f, result_2f]):
        vr = result["verify"]
        if not vr:
            ax.text(0.5, 0.5, "No GT available", ha="center", va="center",
                    transform=ax.transAxes)
            continue
        modes  = sorted(vr.keys())
        errors = [vr[m]["err_pct"] for m in modes]
        colors = ["tomato" if e > 50 else
                  ("orange" if e > 20 else "steelblue") for e in errors]
        ax.bar(modes, errors, color=colors, edgecolor="white")
        ax.axhline(20, color="orange", lw=1.5, ls="--", label="20% threshold")
        ax.axhline(50, color="tomato",  lw=1.5, ls="--", label="50% threshold")
        ax.set_title(f"{result['label']}  —  Amplitude error %")
        ax.set_ylabel("Error (%)"); ax.legend(fontsize=8)
        ax.tick_params(axis="x", rotation=45)
        ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    plt.savefig("plots/lasso_error.png", dpi=200, bbox_inches="tight")
    print("  Saved: plots/lasso_error.png")
    plt.show()


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import os
    os.makedirs("plots", exist_ok=True)

    print("\n" + "="*60)
    print("  LASSO LAMB WAVE DECOMPOSITION")
    print("="*60)

    print("\n[0] Loading dispersion curves...")
    disp = load_dispersion(DISP_FILES)

    # ── Fundamental file (1.33 MHz) ────────────────────────────────────────
    result_f = run_lasso(
        FUNDAMENTAL_FILE, disp,
        label="Fundamental  (1.33 MHz)")

    # ── Second harmonic file (2.66 MHz) ────────────────────────────────────
    result_2f = run_lasso(
        SECOND_HARM_FILE, disp,
        label="2nd Harmonic (2.66 MHz)")

    # ── Summary ───────────────────────────────────────────────────────────
    print("\n" + "="*60)
    print("  SUMMARY — Active modes identified by LASSO")
    print("="*60)
    print(f"\n  Fundamental  active: {result_f['active']}")
    print(f"  2nd Harmonic active: {result_2f['active']}")

    print("\n  Peak amplitudes of interest:")
    for mode in result_f["active"]:
        pk = result_f["peaks"].get(mode, 0.0)
        print(f"    [f]   {mode}: {pk:.6f} nm")
    for mode in result_2f["active"]:
        pk = result_2f["peaks"].get(mode, 0.0)
        print(f"    [2f]  {mode}: {pk:.6f} nm")

    # ── Plots ─────────────────────────────────────────────────────────────
    print("\n[3] Plotting...")
    plot_lasso(result_f, result_2f)
    plot_lasso_error_comparison(result_f, result_2f)

    print("\n" + "="*60 + "\n  DONE\n" + "="*60)